export const guidesMeta = [
  {id:1,title:"Das Alphabet",subtitle:"Letters, Umlauts & Eszett",cat:"Sounds",color:"#1a1a1a",icon:"🔤"},
  {id:2,title:"Vokale & Umlaute",subtitle:"Vowels, Length & Diphthongs",cat:"Sounds",color:"#C62828",icon:"🗣"},
  {id:3,title:"Konsonanten",subtitle:"ch, R, Final Devoicing & More",cat:"Sounds",color:"#1565C0",icon:"👅"},
  {id:4,title:"Betonung",subtitle:"Stress & Prefix Patterns",cat:"Sounds",color:"#2E7D32",icon:"🎵"},
  {id:5,title:"Die vier Fälle",subtitle:"The Four Cases Overview",cat:"Cases",color:"#C62828",icon:"📐"},
  {id:6,title:"Nominativ & Akkusativ",subtitle:"Subject & Direct Object",cat:"Cases",color:"#1565C0",icon:"1️⃣"},
  {id:7,title:"Dativ",subtitle:"Indirect Object & Dative Prepositions",cat:"Cases",color:"#E65100",icon:"2️⃣"},
  {id:8,title:"Wechselpräpositionen",subtitle:"Two-Way Prepositions",cat:"Cases",color:"#6A1B9A",icon:"↔"},
  {id:9,title:"Genitiv",subtitle:"Possession & Formal Usage",cat:"Cases",color:"#00695C",icon:"3️⃣"},
  {id:10,title:"Der, Die, Das",subtitle:"Gender Prediction & Rules",cat:"Nouns",color:"#C62828",icon:"♂♀"},
  {id:11,title:"Pluralbildung",subtitle:"The 5 Plural Patterns",cat:"Nouns",color:"#1565C0",icon:"➕"},
  {id:12,title:"Komposita",subtitle:"Compound Nouns",cat:"Nouns",color:"#2E7D32",icon:"🔗"},
  {id:13,title:"N-Deklination",subtitle:"Weak Nouns",cat:"Nouns",color:"#E65100",icon:"📎"},
  {id:14,title:"Adjektivendungen",subtitle:"Adjective Endings",cat:"Nouns",color:"#6A1B9A",icon:"📝"},
  {id:15,title:"Personalpronomen",subtitle:"Pronouns Across Cases",cat:"Pronouns",color:"#C62828",icon:"👤"},
  {id:16,title:"Du, Ihr, Sie",subtitle:"The Three 'You' Forms",cat:"Pronouns",color:"#1565C0",icon:"🤝"},
  {id:17,title:"Reflexiv & Possessiv",subtitle:"Sich & Mein/Dein/Sein",cat:"Pronouns",color:"#2E7D32",icon:"🔄"},
  {id:18,title:"Präsens",subtitle:"Present Tense & Stem Changes",cat:"Verbs",color:"#C62828",icon:"▶"},
  {id:19,title:"Trennbare Verben",subtitle:"Separable & Inseparable Prefixes",cat:"Verbs",color:"#1565C0",icon:"✂️"},
  {id:20,title:"Modalverben",subtitle:"Can, Must, Should & the Bracket",cat:"Verbs",color:"#E65100",icon:"💪"},
  {id:21,title:"Perfekt",subtitle:"Spoken Past Tense",cat:"Verbs",color:"#6A1B9A",icon:"✓"},
  {id:22,title:"Präteritum",subtitle:"Written/Narrative Past",cat:"Verbs",color:"#00695C",icon:"📖"},
  {id:23,title:"Futur & Konjunktiv",subtitle:"Future, Would & Hypotheticals",cat:"Verbs",color:"#880E4F",icon:"🔮"},
  {id:24,title:"Passiv",subtitle:"Werden + Past Participle",cat:"Verbs",color:"#00838F",icon:"📝"},
  {id:25,title:"Imperativ",subtitle:"Commands & Requests",cat:"Verbs",color:"#4527A0",icon:"❗"},
  {id:26,title:"Hauptsatz",subtitle:"Main Clause V2 Rule",cat:"Word Order",color:"#C62828",icon:"📐"},
  {id:27,title:"Nebensatz",subtitle:"Subordinate Clause Verb-Final",cat:"Word Order",color:"#1565C0",icon:"🔚"},
  {id:28,title:"Fragen & Negation",subtitle:"Nicht vs Kein",cat:"Word Order",color:"#2E7D32",icon:"❓"},
  {id:29,title:"Zahlen & Zeit",subtitle:"Numbers, Time & Dates",cat:"Practical",color:"#E65100",icon:"🔢"},
  {id:30,title:"Verben + Präpositionen",subtitle:"Fixed Preposition Combos",cat:"Practical",color:"#6A1B9A",icon:"🔗"},
  {id:31,title:"Modalpartikeln",subtitle:"Doch, Mal, Ja, Halt...",cat:"Practical",color:"#880E4F",icon:"✨"},
  {id:32,title:"Falsche Freunde",subtitle:"False Friends & Common Errors",cat:"Practical",color:"#C62828",icon:"⚠"},
  {id:33,title:"Formell & Informell",subtitle:"Register, Email & Directness",cat:"Practical",color:"#1a1a1a",icon:"🎩"},
];

export const categories = ["Sounds","Cases","Nouns","Pronouns","Verbs","Word Order","Practical"];

export const catColors = {Sounds:"#1a1a1a",Cases:"#C62828",Nouns:"#1565C0",Pronouns:"#C62828",Verbs:"#C62828","Word Order":"#1565C0",Practical:"#6A1B9A"};
