export const guidesMeta = [
  {id:1,title:"The Alphabet",subtitle:"26 letras, 44+ sonidos",cat:"Pronunciación",color:"#1565C0",icon:"🔤"},
  {id:2,title:"Vowel Sounds",subtitle:"15 vocales vs tus 5",cat:"Pronunciación",color:"#C62828",icon:"🗣"},
  {id:3,title:"Consonant Challenges",subtitle:"Sonidos que no existen en español",cat:"Pronunciación",color:"#2E7D32",icon:"👅"},
  {id:4,title:"Spelling Patterns",subtitle:"La ortografía caótica del inglés",cat:"Pronunciación",color:"#6A1B9A",icon:"✍"},
  {id:5,title:"Stress & Rhythm",subtitle:"El ritmo del inglés americano",cat:"Pronunciación",color:"#E65100",icon:"🎵"},
  {id:6,title:"Simple Present",subtitle:"I work vs I am working",cat:"Verbos",color:"#1565C0",icon:"▶"},
  {id:7,title:"Simple Past",subtitle:"-ed y los 200 irregulares",cat:"Verbos",color:"#C62828",icon:"⏪"},
  {id:8,title:"Future",subtitle:"Will vs going to vs fixin' to",cat:"Verbos",color:"#00695C",icon:"⏩"},
  {id:9,title:"Present Perfect",subtitle:"I have done vs I did",cat:"Verbos",color:"#6A1B9A",icon:"✓"},
  {id:10,title:"Modals",subtitle:"Can, should, must, might could",cat:"Verbos",color:"#E65100",icon:"💪"},
  {id:11,title:"Conditionals",subtitle:"Las 4 condicionales + if I were",cat:"Verbos",color:"#880E4F",icon:"🔀"},
  {id:12,title:"Passive Voice",subtitle:"Was built, is being done, got fired",cat:"Verbos",color:"#00838F",icon:"📝"},
  {id:13,title:"Phrasal Verbs",subtitle:"Get up, get over, get by...",cat:"Verbos",color:"#4527A0",icon:"🧩"},
  {id:14,title:"Articles",subtitle:"A/An vs The vs nada",cat:"Sustantivos",color:"#C62828",icon:"📎"},
  {id:15,title:"Countable vs Uncountable",subtitle:"Much/many, some/any",cat:"Sustantivos",color:"#1565C0",icon:"📊"},
  {id:16,title:"Plurals",subtitle:"Regulares, irregulares y rarezas",cat:"Sustantivos",color:"#2E7D32",icon:"➕"},
  {id:17,title:"Possessives",subtitle:"'s, of, mine, its vs it's",cat:"Sustantivos",color:"#E65100",icon:"🏠"},
  {id:18,title:"Pronouns",subtitle:"Sujeto, objeto, reflexivo",cat:"Pronombres",color:"#1565C0",icon:"👤"},
  {id:19,title:"Y'all",subtitle:"El plural de 'you' que falta",cat:"Pronombres",color:"#C62828",icon:"👥"},
  {id:20,title:"Demonstratives",subtitle:"This, that, every, enough",cat:"Pronombres",color:"#6A1B9A",icon:"👉"},
  {id:21,title:"Adjective Order",subtitle:"La regla secreta que nadie explica",cat:"Adjetivos",color:"#2E7D32",icon:"📐"},
  {id:22,title:"Comparatives",subtitle:"-er/-est, more/most, right good",cat:"Adjetivos",color:"#E65100",icon:"⬆"},
  {id:23,title:"Adverbs",subtitle:"Dónde van y cuándo usar -ly",cat:"Adjetivos",color:"#00695C",icon:"↔"},
  {id:24,title:"In / On / At",subtitle:"Preposiciones sin lógica",cat:"Preposiciones",color:"#C62828",icon:"📍"},
  {id:25,title:"Verb + Preposition",subtitle:"Depend ON, interested IN",cat:"Preposiciones",color:"#4527A0",icon:"🔗"},
  {id:26,title:"Connectors",subtitle:"Because, although, however",cat:"Preposiciones",color:"#1565C0",icon:"🔀"},
  {id:27,title:"Word Order",subtitle:"SVO, do/does/did, tags",cat:"Oraciones",color:"#C62828",icon:"❓"},
  {id:28,title:"Reported Speech",subtitle:"Dijo que... + retroceso de tiempo",cat:"Oraciones",color:"#6A1B9A",icon:"💬"},
  {id:29,title:"Relative Clauses",subtitle:"Who, which, that, whose",cat:"Oraciones",color:"#2E7D32",icon:"🔗"},
  {id:30,title:"Errores Comunes",subtitle:"Falsos amigos y trampas típicas",cat:"Oraciones",color:"#E65100",icon:"⚠"},
  {id:31,title:"Registro y Formalidad",subtitle:"Sir, ma'am, emails, textos",cat:"Práctico",color:"#880E4F",icon:"🎩"},
  {id:32,title:"Modismos",subtitle:"Bless your heart y más",cat:"Práctico",color:"#00695C",icon:"💡"},
  {id:33,title:"Números y Medidas",subtitle:"Imperial, Fahrenheit, propinas",cat:"Práctico",color:"#1565C0",icon:"💲"},
  {id:34,title:"Small Talk",subtitle:"La cultura de la charla casual",cat:"Práctico",color:"#4527A0",icon:"🤝"},
  {id:35,title:"Inglés de Chattanooga",subtitle:"El dialecto local explicado",cat:"Práctico",color:"#E65100",icon:"🏔"},
];

export const categories = ["Pronunciación","Verbos","Sustantivos","Pronombres","Adjetivos","Preposiciones","Oraciones","Práctico"];

export const catColors = {Pronunciación:"#1565C0",Verbos:"#C62828",Sustantivos:"#C62828",Pronombres:"#1565C0",Adjetivos:"#2E7D32",Preposiciones:"#4527A0",Oraciones:"#C62828",Práctico:"#880E4F"};
