import { SimpleGuide } from '../../../components/SimpleGuide';

export function Guide30(){return(<SimpleGuide items={[
  {h:"What is Pidgin (Hawai\u02BBi Creole English)?",b:"A creole language that developed on sugar plantations in the late 1800s-early 1900s from English, Hawaiian, Japanese, Chinese, Portuguese, and Filipino languages mixing together."},
  {h:"Pidgin \u2260 Hawaiian",b:"Pidgin is English-based with Hawaiian loanwords.\nHawaiian is a Polynesian language \u2014 completely different grammar.\n'Da kine' is Pidgin. 'Ke aloha' is Hawaiian.\nThey coexist but are distinct languages."},
  {h:"Hawaiian words commonly used in Pidgin/English",b:"aloha, mahalo, \u02BBohana, lei, luau, hula, wiki, poke (the fish dish), lanai, kama\u02BB\u0101ina, haole, keiki, wahine, k\u0101ne, p\u016Bp\u016B (appetizer), makai/mauka"},
  {h:"Why the distinction matters",b:"Calling Pidgin 'Hawaiian' erases the actual Hawaiian language.\nPidgin is the daily language of many Hawai\u02BBi residents.\nHawaiian is an indigenous Polynesian language in active revitalization.\nBoth deserve respect \u2014 and accurate naming."},
  {h:"Key grammatical differences",b:"Pidgin: 'Da baby stay sleeping' (SVO, English-based)\nHawaiian: 'Ke hiamoe nei ke keiki' (VSO, Polynesian)\nCompletely different language families and structures."},
  {h:"Hawaiian words in Pidgin/English (correct spelling)",b:"Many Hawaiian words used daily in Hawai\u02BBi \u2014 use correct \u02BBokina and kahak\u014D:\nKamaha\u02BBo = \u2018amazing, wonderful\u2019 \u00B7 Kamaaina \u2192 kamaʻ\u0101ina (longtime resident) \u00B7 hale (house) \u00B7 \u02BBohana (family) \u00B7 kai (sea) \u00B7 mauka (toward the mountain) \u00B7 makai (toward the ocean)\nOmitting the marks erases the meaning differences."},
  {h:"Modern Hawaiian vocabulary (living language)",b:"The \u02BBAha P\u016Bnana Leo neologism committee coins terms for modern concepts:\nloulila \u2192 lolouila = computer (from lolo + uila = brain + electricity)\np\u016Bnaewele = internet (p\u016Bna = spring/source + \u02BBaewele = network)\npelekikena = president (from English loanword)\nho\u02BBike na\u02BBauao = television (ho\u02BBike = show + na\u02BBauao = wisdom/broadcast)\nHawaiian is an actively growing language, not a relic."},
]}/>);}
