export const guidesMeta = [
  { id: 1, title: "The 12 Notes", subtitle: "The chromatic alphabet", cat: "Building Blocks", color: "#1a1a1a", icon: "\u{1F3B9}" },
  { id: 2, title: "Intervals", subtitle: "Distance between notes", cat: "Building Blocks", color: "#C62828", icon: "\u2194" },
  { id: 3, title: "The Major Scale", subtitle: "The WWhWWWh formula", cat: "Building Blocks", color: "#1565C0", icon: "\u{1F3B5}" },
  { id: 4, title: "The Minor Scale", subtitle: "Why it sounds 'sad'", cat: "Building Blocks", color: "#6A1B9A", icon: "\u{1F319}" },
  { id: 5, title: "Key Signatures", subtitle: "The Circle of Fifths", cat: "Building Blocks", color: "#2E7D32", icon: "\u{1F511}" },
  { id: 6, title: "How Chords Are Built", subtitle: "Stacking thirds", cat: "Chords", color: "#C62828", icon: "\u{1F9F1}" },
  { id: 7, title: "The 7 Chords in a Key", subtitle: "I ii iii IV V vi vii\u00B0", cat: "Chords", color: "#1565C0", icon: "7\uFE0F\u20E3" },
  { id: 8, title: "Seventh Chords", subtitle: "Adding color & tension", cat: "Chords", color: "#E65100", icon: "\u{1F3A8}" },
  { id: 9, title: "Chord Symbols", subtitle: "Reading Cmaj7, Dm7, G7", cat: "Chords", color: "#6A1B9A", icon: "\u{1F4D6}" },
  { id: 10, title: "Power & Sus Chords", subtitle: "No third, suspended third", cat: "Chords", color: "#2E7D32", icon: "\u26A1" },
  { id: 11, title: "Extensions & Alterations", subtitle: "9ths, 11ths, 13ths", cat: "Chords", color: "#880E4F", icon: "\u{1F527}" },
  { id: 12, title: "Beat & Time Signatures", subtitle: "4/4, 3/4, 6/8 & tempo", cat: "Rhythm", color: "#E65100", icon: "\u{1F941}" },
  { id: 13, title: "Note Values & Rests", subtitle: "Whole, half, quarter, eighth", cat: "Rhythm", color: "#1565C0", icon: "\u266A" },
  { id: 14, title: "Syncopation & Groove", subtitle: "The off-beat magic", cat: "Rhythm", color: "#C62828", icon: "\u{1F57A}" },
  { id: 15, title: "Polyrhythm & Odd Meters", subtitle: "3 against 2, 5/4, 7/8", cat: "Rhythm", color: "#6A1B9A", icon: "\u{1F500}" },
  { id: 16, title: "The I\u2013IV\u2013V", subtitle: "The foundation of Western music", cat: "Progressions", color: "#C62828", icon: "\u{1F3DB}" },
  { id: 17, title: "The I\u2013V\u2013vi\u2013IV", subtitle: "The pop progression", cat: "Progressions", color: "#1565C0", icon: "\u{1F3A4}" },
  { id: 18, title: "Minor Progressions", subtitle: "i\u2013iv\u2013v & beyond", cat: "Progressions", color: "#6A1B9A", icon: "\u{1F311}" },
  { id: 19, title: "The ii\u2013V\u2013I", subtitle: "The jazz backbone", cat: "Progressions", color: "#E65100", icon: "\u{1F3B7}" },
  { id: 20, title: "Cadences", subtitle: "How phrases end (or fake you out)", cat: "Progressions", color: "#2E7D32", icon: "\u{1F3C1}" },
  { id: 21, title: "Modulation", subtitle: "Changing key mid-song", cat: "Progressions", color: "#880E4F", icon: "\u{1F504}" },
  { id: 22, title: "Melody & Scale Degrees", subtitle: "Tension, resolution & home", cat: "Melody", color: "#C62828", icon: "\u{1F3B6}" },
  { id: 23, title: "Song Structure", subtitle: "Verse, chorus, bridge", cat: "Melody", color: "#1565C0", icon: "\u{1F3D7}" },
  { id: 24, title: "Hooks & Motifs", subtitle: "What makes melody memorable", cat: "Melody", color: "#E65100", icon: "\u{1FA9D}" },
  { id: 25, title: "Lyrics & Prosody", subtitle: "Where words meet melody", cat: "Melody", color: "#6A1B9A", icon: "\u270D" },
  { id: 26, title: "Timbre & Tone", subtitle: "Why instruments sound different", cat: "Sound", color: "#1565C0", icon: "\u{1F3B8}" },
  { id: 27, title: "Dynamics & Expression", subtitle: "Soft, loud & everything between", cat: "Sound", color: "#C62828", icon: "\u{1F4E2}" },
  { id: 28, title: "Texture", subtitle: "Thin, thick & layered", cat: "Sound", color: "#2E7D32", icon: "\u{1F9F6}" },
  { id: 29, title: "Beyond Major & Minor", subtitle: "Pentatonic, blues, modes", cat: "Context", color: "#E65100", icon: "\u{1F5FA}" },
  { id: 30, title: "Genre as Dialect", subtitle: "Same notes, different grammar", cat: "Context", color: "#1a1a1a", icon: "\u{1F30D}" },
];

export const categories = ["Building Blocks", "Chords", "Rhythm", "Progressions", "Melody", "Sound", "Context"];

export const catColors = {
  "Building Blocks": "#1a1a1a",
  Chords: "#C62828",
  Rhythm: "#E65100",
  Progressions: "#C62828",
  Melody: "#1565C0",
  Sound: "#1565C0",
  Context: "#1a1a1a",
};
