export const lightTheme = {
  bg: '#FDFBF7',
  headerBg: '#fff',
  borderColor: '#e0dcd5',
  textPrimary: '#1a1a1a',
  textSecondary: '#999',
  textMuted: '#555',
  sidebarBg: '#fff',
  sidebarActiveItemBg: '#f0eeeb',
  sidebarItemText: '#333',
  sidebarItemActiveText: null, // uses guide color
  sidebarSubText: '#999',
  focusColor: '#00695C',
  dotInactive: '#ddd',
  buttonBg: '#fff',
  buttonBorder: '#e0dcd5',
  buttonText: '#555',
  buttonDisabledBg: '#f5f5f5',
  buttonDisabledText: '#ccc',
  overlayBg: 'rgba(0,0,0,0.4)',
  scrollbarThumb: '#d4cfc5',
  contentFont: "system-ui,'Segoe UI',sans-serif",
  shellFont: "system-ui,'Segoe UI',sans-serif",
  outerFont: "'Georgia','Garamond','Times New Roman',serif",
};

export const darkTheme = {
  bg: '#0D0D0D',
  headerBg: '#151515',
  borderColor: '#2a2a2a',
  textPrimary: '#eee',
  textSecondary: '#666',
  textMuted: '#aaa',
  sidebarBg: '#151515',
  sidebarActiveItemBg: '#252525',
  sidebarItemText: '#aaa',
  sidebarItemActiveText: '#fff',
  sidebarSubText: '#555',
  focusColor: '#C62828',
  dotInactive: '#333',
  buttonBg: '#1a1a1a',
  buttonBorder: '#333',
  buttonText: '#aaa',
  buttonDisabledBg: '#111',
  buttonDisabledText: '#444',
  overlayBg: 'rgba(0,0,0,0.6)',
  scrollbarThumb: '#333',
  contentFont: "'Segoe UI','Helvetica Neue',sans-serif",
  shellFont: "'Segoe UI','Helvetica Neue',sans-serif",
  outerFont: "'Segoe UI','Helvetica Neue',sans-serif",
};

export const jazzTheme = {
  ...darkTheme,
  bg: '#121010',
  headerBg: '#1a1510',
  borderColor: '#2a2218',
  sidebarBg: '#1a1510',
  focusColor: '#8D6E63',
  scrollbarThumb: '#3a3025',
};

export const networkTheme = {
  ...lightTheme,
  bg: '#EBF5FB',
  headerBg: '#D6EAF8',
  borderColor: '#AED6F1',
  sidebarBg: '#D6EAF8',
  sidebarActiveItemBg: '#AED6F1',
  sidebarItemText: '#2C3E50',
  sidebarItemActiveText: null,
  sidebarSubText: '#5D6D7E',
  focusColor: '#0277BD',
  dotInactive: '#D4E6F1',
  buttonBg: '#fff',
  buttonBorder: '#AED6F1',
  buttonText: '#2C3E50',
  buttonDisabledBg: '#F2F8FC',
  buttonDisabledText: '#B0C4D8',
  overlayBg: 'rgba(0,0,0,0.4)',
  scrollbarThumb: '#AED6F1',
};
