export const guidesMeta = [
  { id: 1, title: "How Numbers Work", subtitle: "Place value & the number line", cat: "Numbers", color: "#1565C0", icon: "\u{1F522}" },
  { id: 2, title: "Negative Numbers", subtitle: "Debt, temperature & direction", cat: "Numbers", color: "#C62828", icon: "\u2796" },
  { id: 3, title: "Fractions, Decimals & %", subtitle: "Three ways to say the same thing", cat: "Numbers", color: "#2E7D32", icon: "\u{1F355}" },
  { id: 4, title: "Ratios & Proportions", subtitle: "Recipes, maps & exchange rates", cat: "Numbers", color: "#E65100", icon: "\u2696" },
  { id: 5, title: "Order of Operations", subtitle: "Why PEMDAS exists", cat: "Numbers", color: "#6A1B9A", icon: "\u{1F4D0}" },
  { id: 6, title: "Variables & Expressions", subtitle: "The blank in a sentence", cat: "Unknowns", color: "#1565C0", icon: "\u274C" },
  { id: 7, title: "Solving Equations", subtitle: "The balance scale", cat: "Unknowns", color: "#C62828", icon: "\u2696" },
  { id: 8, title: "Inequalities", subtitle: "Ranges, not single answers", cat: "Unknowns", color: "#2E7D32", icon: "\u2194" },
  { id: 9, title: "Formulas You Use", subtitle: "Distance, area, temperature", cat: "Unknowns", color: "#E65100", icon: "\u{1F9EE}" },
  { id: 10, title: "Functions", subtitle: "Input \u2192 rule \u2192 output", cat: "Unknowns", color: "#6A1B9A", icon: "\u2699" },
  { id: 11, title: "Area & Perimeter", subtitle: "How much space, how much fence", cat: "Shapes", color: "#C62828", icon: "\u{1F4CF}" },
  { id: 12, title: "Volume & Surface Area", subtitle: "How much it holds", cat: "Shapes", color: "#1565C0", icon: "\u{1F4E6}" },
  { id: 13, title: "Angles & Triangles", subtitle: "180\u00B0 and Pythagoras", cat: "Shapes", color: "#2E7D32", icon: "\u{1F4D0}" },
  { id: 14, title: "Circles", subtitle: "\u03C0 and the universal ratio", cat: "Shapes", color: "#E65100", icon: "\u2B55" },
  { id: 15, title: "Coordinate Geometry", subtitle: "The x-y grid as a map", cat: "Shapes", color: "#6A1B9A", icon: "\u{1F4CD}" },
  { id: 16, title: "Linear Growth", subtitle: "y = mx + b in real life", cat: "Growth", color: "#1565C0", icon: "\u{1F4C8}" },
  { id: 17, title: "Exponential Growth", subtitle: "Doubling, compound interest", cat: "Growth", color: "#C62828", icon: "\u{1F680}" },
  { id: 18, title: "Logarithms", subtitle: "The inverse of exponentials", cat: "Growth", color: "#2E7D32", icon: "\u{1F50D}" },
  { id: 19, title: "Sequences & Series", subtitle: "Patterns that repeat", cat: "Growth", color: "#E65100", icon: "\u{1F517}" },
  { id: 20, title: "Probability Basics", subtitle: "How likely is it?", cat: "Growth", color: "#6A1B9A", icon: "\u{1F3B2}" },
  { id: 21, title: "Mean, Median, Mode", subtitle: "Finding the center", cat: "Data", color: "#C62828", icon: "\u{1F4CA}" },
  { id: 22, title: "Spread & Distribution", subtitle: "Bell curves & standard deviation", cat: "Data", color: "#1565C0", icon: "\u{1F514}" },
  { id: 23, title: "Reading Graphs", subtitle: "How charts tell (and lie about) stories", cat: "Data", color: "#2E7D32", icon: "\u{1F4C9}" },
  { id: 24, title: "Correlation vs Causation", subtitle: "The most important distinction", cat: "Data", color: "#E65100", icon: "\u{1F500}" },
  { id: 25, title: "Probability in Practice", subtitle: "Why 99% accurate doesn't mean what you think", cat: "Data", color: "#6A1B9A", icon: "\u{1F3E5}" },
  { id: 26, title: "Sampling & Bias", subtitle: "Why polls get it wrong", cat: "Data", color: "#880E4F", icon: "\u{1F3AF}" },
  { id: 27, title: "Compound Interest", subtitle: "Time \u00D7 money \u00D7 patience", cat: "Money", color: "#1565C0", icon: "\u{1F4B0}" },
  { id: 28, title: "Loans & Debt", subtitle: "How amortization really works", cat: "Money", color: "#C62828", icon: "\u{1F3E6}" },
  { id: 29, title: "Taxes & Brackets", subtitle: "Marginal vs effective rates", cat: "Money", color: "#2E7D32", icon: "\u{1F4CB}" },
  { id: 30, title: "Risk & Expected Value", subtitle: "Should I take the deal?", cat: "Money", color: "#E65100", icon: "\u{1F3B0}" },
  { id: 31, title: "Estimation", subtitle: "Back-of-envelope math", cat: "Wild", color: "#1565C0", icon: "\u{1F914}" },
  { id: 32, title: "Math You Already Do", subtitle: "Cooking, tipping, driving, shopping", cat: "Wild", color: "#2E7D32", icon: "\u{1F6D2}" },
];

export const categories = ["Numbers", "Unknowns", "Shapes", "Growth", "Data", "Money", "Wild"];

export const catColors = {
  Numbers: "#1565C0",
  Unknowns: "#C62828",
  Shapes: "#2E7D32",
  Growth: "#1565C0",
  Data: "#C62828",
  Money: "#2E7D32",
  Wild: "#1565C0",
};
